version: '3.7'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.0
    container_name: elasticsearch1
    environment:
      - node.name=elasticsearch1
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=elasticsearch1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=_eth0_
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
    ports:
      - 9200:9200
      - 9300:9300
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.0
    container_name: elasticsearch2
    environment:
      - node.name=elasticsearch2
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=elasticsearch1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=_eth0_
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
    ports:
      - 9201:9200
  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.0
    container_name: elasticsearch3
    environment:
      - node.name=elasticsearch3
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=elasticsearch1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=_eth0_
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
    ports:
      - 9202:9200
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.6.0
    volumes:
      - "./sources:/sources"
    command: ["/sources/wait-for-it.sh", "elasticsearch1:9200", "--", "logstash", "-f", "/sources/logstash.conf"]
    networks:
      - elastic
    depends_on:
      - elasticsearch1
      - elasticsearch2
      - elasticsearch3
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.6.0
    container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_HOSTS: http://elasticsearch1:9200/
    ports:
      - 5601:5601
    depends_on:
    - elasticsearch1
    - elasticsearch2
    - elasticsearch3
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
networks:
  elastic:
